---
- name: Provisioning servers
  hosts: all
  become: yes
  tasks:
    - name: Update repository on Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install chrony on Ubuntu
      apt:
        name: "{{item}}" 
        state: present
      when: ansible_distribution == "Ubuntu"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip 

    - name: Update repository on CentOS
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Install chrony on CentOS
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip 

    - name: Start chrony service on Ubuntu
      service:
        name: chrony
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start chrony service on CentOS
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Banner file
      copy:
        content: '#This server is managed by ansible. NO manual changes please.'
        dest: /etc/motd

    - name: Create a folder 
      file:
        path: /opt/test21
        state: directory

    - name: Deploy ntp agent conf on centos
      template:
        src: templates/chrony-conf_centos
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "CentOS"
      notify:
        - reStart service on centos


    - name: Deploy ntp agent conf on ubuntu
      template:
        src: templates/chrony-conf_ubuntu
        dest: /etc/chrony.conf
        backup: yes
      when: ansible_distribution == "Ubuntu"
      notify:
        - reStart service on ubuntu

  handlers:
    - name: reStart service on centos
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"


    - name: reStart service on ubuntu
      service:
        name: chrony
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"
