---
- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Service start
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy index file
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
        backup: yes

